version: '3.1'

services:

  bagisto-php-apache:
    build:
      args:
        container_project_path: /var/www/html/
        host_project_path: ./bagisto/
        uid: 1000
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    image: bagisto-php-apache
    ports:
      - 80:80
    volumes:
      - ./bagisto/:/var/www/html/

  bagisto-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./.configs/init.sql:/tmp/databases/init.sql
      - mysql-data:/var/lib/mysql/
    command: mysqld --init-file="/tmp/databases/init.sql"

  bagisto-phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: bagisto-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 3333:80

volumes:
  mysql-data: